spring.application.name=api-gateway

server.port=8080

# ===============================
# Eureka Client Configuration
# ===============================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# API Gateway Routes
# ===============================

# User Service
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**

# Customer Service
spring.cloud.gateway.server.webflux.routes[1].id=customer-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/customers/**

# Billing Service
spring.cloud.gateway.server.webflux.routes[2].id=billing-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/bills/**

# Payment Service
spring.cloud.gateway.server.webflux.routes[3].id=payment-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/payments/**

# Notification Service
spring.cloud.gateway.server.webflux.routes[4].id=notification-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/notifications/**


# ===============================
# Actuator Configuration
# ===============================

management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted